# Generated by Django 6.0.7 on 2026-07-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('numero_serie', models.CharField(max_length=50, unique=True, verbose_name='Número de Serie')),
                ('registro_invima', models.CharField(max_length=50, verbose_name='Registro INVIMA')),
                ('ubicacion', models.CharField(help_text='Ej: Consultorio 1, Sala de Procedimientos', max_length=100)),
                ('fecha_ultimo_mantenimiento', models.DateField(verbose_name='Último Mantenimiento')),
                ('fecha_proximo_mantenimiento', models.DateField(verbose_name='Próximo Mantenimiento')),
            ],
        ),
    ]
