# Generated by Django 6.0.7 on 2026-08-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipomedico',
            options={'verbose_name': 'Equipo Médico', 'verbose_name_plural': 'Equipos Médicos'},
        ),
        migrations.AddField(
            model_name='equipomedico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='equipos/', verbose_name='Fotografía del Equipo'),
        ),
    ]
