# Generated by Django 6.1 on 2026-08-15 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_alter_equipomedico_options_equipomedico_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('calibracion', 'Calibración')], default='preventivo', max_length=20)),
                ('fecha_mantenimiento', models.DateField(verbose_name='Fecha del Mantenimiento')),
                ('tecnico_responsable', models.CharField(max_length=150, verbose_name='Técnico Responsable')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones / Detalles')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo ($)')),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='equipos.equipomedico')),
            ],
        ),
    ]
